apiVersion: v1
kind: Service
metadata:
  name: kafkab-lb-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kafkab-0
  ports:
    - name: external
      port: 9094
      targetPort: external
---
apiVersion: v1
kind: Service
metadata:
  name: kafkab-lb-1
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kafkab-1
  ports:
    - name: external
      port: 9094
      targetPort: external
---
apiVersion: v1
kind: Service
metadata:
  name: kafkab-lb-2
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kafkab-2
  ports:
    - name: external
      port: 9094
      targetPort: external
