apiVersion: v1
kind: Pod
metadata:
  name: geoip-asn-loader
spec:
  restartPolicy: Never
  containers:
  - name: loader
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: geoip-asn-volume
      mountPath: /mnt/geoip
  volumes:
  - name: geoip-asn-volume
    persistentVolumeClaim:
      claimName: geoip-asn-pvc
