apiVersion: v1
kind: Service
metadata:
  name: logstash-lb
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: logstash
  type: LoadBalancer
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
