replicaCount: 3

image:
  registry: docker.io
  repository: bitnami/logstash
#  tag: 8.3.3-debian-11-r5

nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: NotIn
        values:
        - workers-node-eac0c8
        - workers-node-c83aa9

extraVolumes:
  - name: geoip-dir
    emptyDir: {}
  - name: logstash-certs
    secret:
      secretName: logstash-tls-secret

extraVolumeMounts:
  - name: geoip-dir
    mountPath: /mnt/geoip
  - name: logstash-certs
    mountPath: /usr/share/logstash/config/certs
    readOnly: true

initContainers:
  - name: copy-geoip
    image: equalitie/baskerville_geoip:latest
    command: ["sh", "-c", "cp /data/GeoLite2-ASN.mmdb /mnt/geoip/"]
    volumeMounts:
      - name: geoip-dir
        mountPath: /mnt/geoip

input: |-
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "/usr/share/logstash/config/certs/certificate.pem"
    ssl_key => "/usr/share/logstash/config/certs/key.pem"
    ssl_verify_mode => "none"
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/caroot.pem"]
  }

output: |-
  if "farmal.in" in [message] {
    stdout {
      codec => line {
        format => "@@@ RAW match: %{message}"
      }
    }
  }
  if ![client_request_host] {
    stdout {
      codec => line {
        format => "@@@ Missing client_request_host! Event: %{message}"
      }
    }
  }
  if ![kafka_topic] {
    stdout {
      codec => line {
        format => "@@@ Missing [kafka_topic]! Event: %{message}"
      }
    }
  }
  kafka {
    bootstrap_servers => "kafkab-0.kafkab-headless.default.svc.cluster.local:9093,kafkab-1.kafkab-headless.default.svc.cluster.local:9093,kafkab-2.kafkab-headless.default.svc.cluster.local:9093"
    topic_id => "%{[kafka_topic]}"
    acks => "1"
    codec => "json"
    partitioner => "default"
    message_key => "%{client_request_host}"
  }
  kafka {
    bootstrap_servers => "kafka9-0.kafka9-headless.default.svc.cluster.local:9093,kafka9-1.kafka9-headless.default.svc.cluster.local:9093,kafka9-2.kafka9-headless.default.svc.cluster.local:9093"
    topic_id => "%{[kafka_topic]}"
    acks => "1"
    codec => "json"
    partitioner => "default"
    message_key => "%{client_request_host}"
  }




filter: |-
  mutate {
    gsub => [ "message", '"http_response_code":\s*000', '"http_response_code":"000"' ]
  }
  if [http_response_code] == "000" {
    mutate {
      replace => { "http_response_code" => "200" }
    }
    mutate {
      convert => { "http_response_code" => "integer" }
    }
  }
  
  if [@metadata][kafka][topic] == "filebeat_deflect_access" or 
   [@metadata][kafka][topic] == "filebeat_deflect_access_temp" or
   [fields][log_topic] == "filebeat_deflect_access" or 
   [fields][log_topic] == "filebeat_deflect_access_temp" {
    mutate{
      add_field => { "kafka_topic" => "logstash_deflect.log" }
    }
    date {
      match => [ "time_local", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "datestamp"
      remove_field => [ "time_local" ]
    }
  }

  if [@metadata][kafka][topic] == "filebeat_banjax" or 
    [@metadata][kafka][topic] == "filebeat_banjax_access_temp" or
    [fields][log_topic] == "filebeat_banjax" or
    [fields][log_topic] == "filebeat_banjax_access_temp" {
    mutate{
      add_field => { "kafka_topic" => "logstash_banjax" }
    }
    date {
      match => [ "timestring", "yyyy-MM-dd'T'HH:mm:ss" ]
      target => "datestamp"
      remove_field => [ "timestring" ]
    }
    if [path] {
      grok {
        match => { "path" => "%{URIPATH:client_url}(%{URIPARAM:querystring})?" }
      }
    }
  }

  if [client_request_host] {
    mutate {
      add_field => { "message_key_safe" => "%{client_request_host}" }
    }
  } else {
    mutate {
      add_field => { "message_key_safe" => "unknown" }
    }
  }

  mutate {
    copy => {"client_request_host" => "client_request_host_original"}
    gsub => [ "client_request_host", "^www\.", "" ]
  }

  geoip {
    source => "client_ip"
    target => "geoip0"
    default_database_type => "City"
    fields => [ "city_name", "continent_code", "country_code2", "country_name", "location", "timezone" ]
  }

  geoip {
    source => "client_ip"
    target => "geoip_asn"
    database => "/mnt/geoip/GeoLite2-ASN.mmdb"
    fields => ["AUTONOMOUS_SYSTEM_NUMBER", "AUTONOMOUS_SYSTEM_ORGANIZATION"]
  }

  mutate {
    copy => { "[geoip0][geo][country_iso_code]" => "[geoip][country_code2]" }
    copy => { "[geoip0][geo][country_name]" => "[geoip][country_name]" }
    copy => { "[geoip0][geo][timezone]" => "[geoip][timezone]" }
    copy => { "[agent][name]" => "[edge]" }
  }

  useragent {
    source => "client_ua"
    target => "user_agent"
  }
  mutate {
    remove_field => [
       "@timestamp",
       "@version",
       "geoip0"
    ]
  }

  if ";" in [content_type] {
    mutate {
      split => { "content_type" => ";" }
      add_field => { "new_content_type" => "%{[content_type][0]}" }
    }
    mutate {
      rename => { "new_content_type" => "content_type" }
    }
  }
  mutate {
    remove_field => [
      "event",
      "@timestamp",
      "@version",
      "type",
      "upstream_addr",
      "upstream_status",
      "upstream_response_time",
      "upstream_header_time",
      "upstream_connect_time",
      "upstream_bytes_sent",
      "upstream_bytes_received",
      "client_user",
      "referer",
      "refererdomain",
      "loc_out",
      "proxy_host",
      "proxy_port",
      "forwardedfor",
      "request_time",
      "filter_start",
      "rule_type",
      "banjax_error",
      "request_id",
      "log",
      "fields",
      "input",
      "host"
    ]
  }

