{
 "title": "Traffic Light",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "aletihadpress,shadyplus,splendits,observatorioni,vanguardiasv,report,hawarnews,laorejaroja,nordis,nkd,360stepeni,3ayin,7al,abortionfinder,abortionfunds,academicfreedomsby,acc.tni.org,accessaccountability,actforfreedomnow,actwithus,afondoedomex,altaghyeer,altareeq,aman.zone,amnestyshop,analytics,angpangako,antifa,arsod,aseansogiecaucus,atlantaantifa,aurdip,auz8anj1,avishanx,baharpix,balcanicaucaso,balochcampaign,bankwatch,baotiengdan,bdsquebec,beauswan,bestonlinegamesqq288,beyondactivismo,bidoon,blackfutureslab,bolya,book.xxs8.com:80,books,boveda,bowlathon,bpdwatch,btselem,burmacampaign,buzoter,bvbv.org.cn.smex.org,cadenademando,caldh,cartochaco,cci,ccij,cda.gov.co,censorship,center-action,centre1,cercavamolapace,changecopyright,charlotteuprising,chenpoo,cherkasy24,childrenontheedge,chroniquepalestine,cmiguate,cn.vot.org,conaie,confeniae,congresocienciasambientalesrcfa,conquer-and-divide,contracorriente,contraloriadecordoba,contratacionespublicas,contrepoints,crimean-process,criterio,culturesofresistance,culturesofresistancefilms,curul43,cvu,d235549cojqgau,d3clylu4rhwpu5,darfur24,dash.mmdc.ru,dashadmin,dashboard,datosprotegidos,dbev.site.smex.org,dbom.site.smex.org,dedmorozprotiv,defakto.support,deflect,deflect.network,designaction,develop,dgzxzdh,diegocupolo,digari,digsec,dmgburmese,dojensgara,dominemoslatecnologia,donate.indigo.kg,downtoearth-indonesia,dss380,dukq.site.smex.org,ecuadortoday,einnews,ekuatorial,elreporte,eltuz,emafund,empoerteuch,enjambre,ens.org.co,eqpress.equalit.ie,equalit,equalrights-centrasia,escueladeseguridaddigital,eslinde,ethicalshop,extinctionrebellion,facetz,farmal,fastwebserver,feminisminindia,fergana,fergananews,findyourb,firstvoicesindigenousradio,foazuay,focusaleppo,forestpeoples,forrights,forstamt-dingenskirchen,freedomlounge,freedomonlinecoalition,freerunet,freethemnow,fundabortion,fundabortionnow,fundacionsantamaria,fundathon,fundraising,futureoceans,gaytest,gbsurvivors,gdwellbing,genderdings,genderit,generationjustice,ggjalliance,globalbersih,gobernanzadeinternet,gobiernoabiertomx,gp-digital,greenhost,gubernia,gzlixue1688,hackedalert,haliangjidian,hamdamapp,hawarnews,help.mmdc.ru,helpdesk,hetzner20,hodnews,hphcolombia,hrcspb,httpheader,huridocs,hurisa,iccpg,ide.parents.physk.network,idefend,ifweweresyrian,ihadanabortion,ijvcanada,imap.smex.org,imemc,impactiran,inbox7,indigo,indymedia,infoactivismo,infocongo,infopacific,informaterompeelmiedo,informator,inkyfada,inredh,ip-145-239-7,ip-176-31-125,ip-46-105-96,ip-51-77-116,ip-94-23-30,ipdb-bot,ippogroup,irancybercrime,irrp,janinewarner,jfp.org.ua,jillianfriedmanlaw,jisr,jorgeluissierra,jorgeviejo,joshuaprovoste,journalistsforrights,juvenilejusticecentre,jvpdc,kactus,kalemon,kavkaz-uzel,kboo,kevorkaghazarian,khosq,klimaprotest,kompetentia,kotsubynske,ladobe,lahistoria,larepublica,lasaqf,learning,level-up,lgbt-hiv,lgbtru,ligacontraelsilencio,linkswende,localhost,lostbaku,luchadoras,m4bl,macholand,majlismonitor,malina,manandlaw,mangoba,marsadak,marxismuss,mayfirst,mazaya-women,mekongeye,memorandum-online,menschliche-asylpolitik,mmdc,mobile,monitor.prod.deflect.ca,msftncsi,mtvburmaaction,mutabar,nama,namnam,neonmona,newsyrian,newwebsite,nextcloud,nielo,nnaf,north-shore,northkensingtonlibrary,nrrdo,nrrdoradio,ntenegro-199516o,nubareports,nucnet,nujp,nuntiare,nyaaf,oasdeflect,occupationfreedc,online,onlineoffline,open-archive,openearth,opennet,openrunet,opera-de-marseille,opera-marseille,opera-municipal-de-marseille,opera-municipal-marseille,operademarseille,operamarseille,operamunicipaldemarseille,operamunicipalmarseille,oporacv,orgsafe,pagina3,palarchive,palestinechronicle,paljourneys,palliativespb,palmuseum,papuansbehindbars,parniplus,passwords,pen-international,periodistasdeapie,philippinehumanrights,piedepagina,points-of-view,poneytelecom,pooshema,pop3.smex.org,povorkaponosa,prep.love,press,preziso,programaacua,progres,protege,pryrodni,qurium,radiozones,raichali,rap23,rappr-rppsn,rcmediafreedom,rds.org.co,rds.org.co:443,redesquintopoder,rohingya,rohingyakhobor,rojava,royafm,ruidocdmx,sabzbashim,scoop,scoopcons,secrethistory,securedservers,segudigital,seguridaddigital,semillas,sentiido,seremoslasultimas,server-hosting,slobodenpecat,smex,sobytiya,soyou24.prod.deflect.ca,spartak,squat,stagedash,stagedashadmin,staging,stopblackface,stopthewall,subdomain2,sudouk,summit2018,supremainjusticia,t-action-team,tapol,tasinhorjun,tchrd,technology,telegram,teprotejo,test.irrp.org.ua,testnewsite2,thamhoaformosa,the-tower,theinvisiblewalls,thelinknewspaper,tibet,tibettimes,timep,tjwg,tni.org,tni.org:443,transparency-everywhere,tuperiodico,typo,uzmetronom,value-brand,valuebrand,veeble20,venlyct2a,verafiles,vh1burmaaction,villanabebidaazucarada,vitaliev,vot.org,vot.org:80,wambra,watchteam,weihekj,wetestify,whatisaggregate,wiki-arch,worldstream,wozazimbabwe,wxsongxin,xinruijinshu,xinzhekeji,xrqc,yanshengdz,yementimesradio,yenfon,yenijurnalist,yjtzg,yjzzk,ykcdx,zabeba,zaitonmag,zambianwatchdog,zambiawatchdog,zennolab"
   }
  ]
 },
 "panels": [
  {
   "title": "IPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as anomaly\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand prediction = 1 and challenged = 0\ngroup by 1 order by 1"
    },
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as attack\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand challenged = 1 --and (low_rate_attack = 0 or low_rate_attack isnull)\ngroup by 1 order by 1"
    },
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as regular\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand prediction = 0 and challenged = 0\ngroup by 1 order by 1"
    },
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as low_rate_attack\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand low_rate_attack = 1 and challenged = 1\ngroup by 1 order by 1"
    }
   ]
  },
  {
   "title": "Regular",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand prediction = 0 and challenged = 0\n"
    }
   ]
  },
  {
   "title": "Anomaly",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE \n$__timeFilter(stop) \nand target = '$Host' \nand prediction = 1 and challenged = 0"
    }
   ]
  },
  {
   "title": "Challenge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand challenged = 1 and low_rate_attack = 0\n"
    }
   ]
  },
  {
   "title": "Low Rate Challenge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand low_rate_attack = 1 and challenged = 1\n"
    }
   ]
  },
  {
   "title": "Passed Challenge",
   "type": "stat",
   "description": "The total number of passed challenge IPs",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct ip)\nFROM request_sets WHERE $__timeFilter(stop) and target = '$Host' \nand challenged = 1 and challenge_passed = 1 "
    }
   ]
  }
 ]
}