apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spark
  name: notebook-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cinder-high-speed