metadata:
  name: postprocessing
  namespace: default
  selfLink: >-
    /apis/argoproj.io/v1alpha1/namespaces/default/workflowtemplates/postprocessing
  uid: 3e886157-b580-4571-bb7c-b95a2a4e7cc9
  resourceVersion: '15528736'
  generation: 11
  creationTimestamp: '2021-03-15T15:59:15Z'
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
  managedFields:
    - manager: argo
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2021-03-29T16:24:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:workflows.argoproj.io/creator': {}
        'f:spec':
          .: {}
          'f:arguments':
            .: {}
            'f:parameters': {}
          'f:entrypoint': {}
          'f:templates': {}
spec:
  templates:
    - name: spark-submit
      inputs:
        parameters:
          - name: baskerville_image
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: '{{inputs.parameters.baskerville_image}}'
        command:
          - sh
        args:
          - /opt/spark/bin/spark-submit
          - '--master'
          - 'k8s://https://kubernetes.default.svc'
          - '--deploy-mode'
          - cluster
          - '--conf'
          - spark.kubernetes.namespace=default
          - '--conf'
          - spark.kubernetes.container.image=sparkimage
          - '--conf'
          - spark.executor.instances=3
          - '--name'
          - postprocessing
          - '--conf'
          - spark.kubernetes.pyspark.pythonVersion=3
          - '--conf'
          - spark.kubernetes.memoryOverheadFactor=0.1
          - '--conf'
          - spark.memory.fraction=0.1
          - '--conf'
          - spark.kubernetes.driver.request.cores=1
          - '--conf'
          - spark.kubernetes.driver.limit.cores=1
          - '--conf'
          - spark.kubernetes.executor.request.cores=2
          - '--conf'
          - spark.kubernetes.executor.limit.cores=2
          - '--conf'
          - spark.driver.memory=2G
          - '--conf'
          - spark.executor.memory=3G
          - '--jars'
          - >-
            local:///usr/local/baskerville/data/jars/hadoop-aws-2.7.1.jar,local:///usr/local/baskerville/data/jars/aws-java-sdk-1.7.4.jar,local:///usr/local/baskerville/data/jars/spark-iforest-2.4.0.99.jar,local:///usr/local/baskerville/data/jars/postgresql-42.2.4.jar,local:///usr/local/baskerville/data/jars/spark-streaming-kafka-0-8-assembly_2.11-2.4.0.jar,local:///usr/local/baskerville/data/jars/spark-redis_2.11-2.5.0-SNAPSHOT-jar-with-dependencies.jar
          - '--conf'
          - >-
            spark.kubernetes.container.image={{inputs.parameters.baskerville_image}}
          - /usr/local/baskerville/src/baskerville/main.py
          - postprocessing
          - '-c'
          - /usr/local/baskerville/conf/postprocessing.yaml
        resources: {}
        imagePullPolicy: Always
  entrypoint: spark-submit
  arguments:
    parameters:
      - name: baskerville_image
        value: 'mazhurin/baskerville:latest'
