image:
  registry: docker.io
  repository: bitnamilegacy/grafana
#  tag: "7.3.4"
  tag: 12.1.1-debian-12-r0

admin:
  existingSecret: grafana-admin
  existingSecretUserKey: admin-user
  existingSecretPasswordKey: admin-password

nodeSelector:
  nodepool: "postgres"

imageRenderer:
  nodeSelector:
    nodepool: "postgres"

dashboardsProvider:
  enabled: true

service:
  type: ClusterIP

datasources:
  secretName: datasource-secret
