{
 "title": "Anomalies",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Host", "label": "Host", "query": "testhost" }
  ]
 },
 "panels": [
  {
   "title": "$Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as anomalies\nFROM request_sets_y2020_w20 WHERE $__timeFilter(stop) and target = '$Host' \n--and prediction = 1 \nand score >= 52/100.0\ngroup by 1 order by 1\n"
    },
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), count(distinct ip) as regular\nFROM request_sets_y2020_w20 WHERE $__timeFilter(stop) and target = '$Host' \n--and prediction = 0 \nand score < 52/100.0\ngroup by 1 order by 1\n"
    }
   ]
  },
  {
   "title": "Attack score",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), target, avg(case when score >= 52/100.0 then 100.0 else 0 end) as anomalies\nFROM request_sets_y2020_w20 WHERE $__timeFilter(stop) \ngroup by 1, 2 \nHAVING COUNT(stop) > 20 \norder by 1\n\n"
    }
   ]
  },
  {
   "title": "Total Unique IPs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(stop, '2m'), target, count(distinct ip) as total\nFROM request_sets_y2020_w20 WHERE $__timeFilter(stop) \ngroup by 1,2 \norder by 1\n"
    }
   ]
  }
 ]
}