{
 "title": "Banjax Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "baskerville_proxy_process_net_connections_currently_open",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_proxy_process_net_connections_currently_open"
    }
   ]
  },
  {
   "title": "Active challenges per Banjax instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "baskerville_num_of_challenges" }
   ]
  },
  {
   "title": "baskerville_proxy_process_cache_ram_cache_total_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_proxy_process_cache_ram_cache_total_bytes"
    }
   ]
  },
  {
   "title": "baskerville_proxy_process_http_current_active_client_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_proxy_process_http_current_active_client_connections"
    }
   ]
  },
  {
   "title": "baskerville_proxy_process_cache_ram_cache_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_proxy_process_cache_ram_cache_bytes_used"
    }
   ]
  },
  {
   "title": "baskerville_proxy_process_cache_percent_full",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_proxy_process_cache_percent_full"
    }
   ]
  },
  {
   "title": "baskerville_proxy_process_cache_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_proxy_process_cache_bytes_total"
    }
   ]
  },
  {
   "title": "Num of IPs that failed challenger",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_ip_failed_challenge_on_website_total"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_proxy_process_traffic_server_memory_rss"
    }
   ]
  }
 ]
}