{
 "title": "Baskerville Performance Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Number of Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "baskerville_progress_current_number_of_requests"
    }
   ]
  },
  {
   "title": "AVG Number of Sessions/ Subsets",
   "type": "singlestat",
   "description": "Per batch.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_current_subsets_count"
    }
   ]
  },
  {
   "title": "Avg Feature Value",
   "type": "graph",
   "description": "Across Hosts, for each run.",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_progress_avg_feature_value"
    }
   ]
  },
  {
   "title": "AVG host prediction {host=\"equalit.ie\"}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_progress_avg_host_prediction{host=\"equalit.ie\"}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_progress_current_number_of_requests"
    }
   ]
  },
  {
   "title": "Total # of requests since Baskerville started",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "baskerville_progress_total_number_of_requests"
    }
   ]
  },
  {
   "title": "RequestSet Cache current item count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "baskerville_progress_request_set_cache_len"
    }
   ]
  },
  {
   "title": "AVG Time (seconds) it gets Baskerville to complete all steps for one pipeline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance__get_df_sum + baskerville_performance__feature_extraction_sum +baskerville_performance__group_by_sum"
    }
   ]
  },
  {
   "title": "Current Alerts Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "baskerville_current_alerts_count"
    }
   ]
  },
  {
   "title": "Total Alerts Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "baskerville_current_alerts_count"
    }
   ]
  },
  {
   "title": "Total # of RequestSets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 17 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "baskerville_currrent_request_sets_count"
    }
   ]
  },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 } },
  {
   "title": "Current number of subsets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "baskerville_current_subsets_count"
    }
   ]
  },
  {
   "title": "# of times _get_df has been executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "baskerville_performance__get_df_count"
    }
   ]
  },
  {
   "title": "# of times _group_by has been executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "baskerville_performance__group_by_count"
    }
   ]
  },
  {
   "title": "# of times feature_extraction has been executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 28 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "baskerville_performance__feature_extraction_count"
    }
   ]
  },
  {
   "title": "# of times predict has been executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "baskerville_performance__predict_count"
    }
   ]
  },
  {
   "title": "# of times \"save\" has been executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 28 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "baskerville_performance__save_count"
    }
   ]
  },
  {
   "title": "# of times update has been executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "baskerville_performance__update_count"
    }
   ]
  },
  {
   "title": "AVG get_df time (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance__get_df_sum"
    }
   ]
  },
  {
   "title": "AVG group_by time (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance__group_by_sum"
    }
   ]
  },
  {
   "title": "AVG predict time (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance__predict_sum"
    }
   ]
  },
  {
   "title": "AVG feature_extraction time (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance__feature_extraction_sum"
    }
   ]
  },
  {
   "title": "AVG save time (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance__save_sum"
    }
   ]
  },
  {
   "title": "AVG update time (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance__update_sum"
    }
   ]
  },
  {
   "title": "Feature details",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "content": "# Feature details\nWe can see here which feature takes the longest to compute"
  },
  {
   "title": "AVG path_depth_sum time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_path_depth_sum"
    }
   ]
  },
  {
   "title": "AVG path_depth_variance time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_path_depth_variance_sum"
    }
   ]
  },
  {
   "title": "AVG path_max time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_path_max_sum"
    }
   ]
  },
  {
   "title": "AVG path_total time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_path_total_sum"
    }
   ]
  },
  {
   "title": "AVG payload_size time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_payload_size_sum"
    }
   ]
  },
  {
   "title": "AVG query_per_page time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_query_per_page_sum"
    }
   ]
  },
  {
   "title": "AVG query_total time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_query_total_sum"
    }
   ]
  },
  {
   "title": "AVG ratio2html_css time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_ratio2html_css_sum"
    }
   ]
  },
  {
   "title": "AVG ratio2html_image time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_ratio2html_image_sum"
    }
   ]
  },
  {
   "title": "AVG ratio2html_js time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_ratio2html_js_sum"
    }
   ]
  },
  {
   "title": "AVG request_interval_variance time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_request_interval_variance_sum"
    }
   ]
  },
  {
   "title": "AVG request_total time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_request_total_sum"
    }
   ]
  },
  {
   "title": "AVG response_4xx_rate time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_response_4xx_rate_sum"
    }
   ]
  },
  {
   "title": "AVG ua_total time to compute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "baskerville_performance_feature_ua_total_sum"
    }
   ]
  }
 ]
}