{
 "title": "Spark Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "driver_DAGScheduler_job_activeJobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\".*driver_DAGScheduler_job_activeJobs\"}"
    }
   ]
  },
  { "title": "DAG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "driver_CodeGenerator_compilationTime sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_CodeGenerator_compilationTime_sum\"}"
    }
   ]
  },
  {
   "title": "driver_CodeGenerator_generatedClassSize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_CodeGenerator_generatedClassSize\"}"
    }
   ]
  },
  {
   "title": "driver_CodeGenerator_generatedMethodSize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_CodeGenerator_generatedMethodSize\"}"
    }
   ]
  },
  {
   "title": "driver_CodeGenerator_sourceCodeSize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_CodeGenerator_sourceCodeSize\"}"
    }
   ]
  },
  { "title": "Block Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "driver_BlockManager_disk_diskSpaceUsed_MB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_BlockManager_disk_diskSpaceUsed_MB\"}"
    }
   ]
  },
  {
   "title": "driver_BlockManager_memory_maxMem_MB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_BlockManager_memory_maxMem_MB\"}"
    }
   ]
  },
  {
   "title": "driver_BlockManager_memory_maxOffHeapMem_MB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_BlockManager_memory_maxOffHeapMem_MB\"}"
    }
   ]
  },
  {
   "title": "driver_BlockManager_memory_memUsed_MB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_BlockManager_memory_memUsed_MB\"}"
    }
   ]
  },
  {
   "title": "driver_BlockManager_memory_maxOnHeapMem_MB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_BlockManager_memory_maxOnHeapMem_MB\"}"
    }
   ]
  },
  {
   "title": "driver_BlockManager_memory_remainingMem_MB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*driver_BlockManager_memory_remainingMem_MB\"}"
    }
   ]
  }
 ]
}