# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        git clone -b categorical_features https://github.com/equalitie/spark-iforest.git
        cd spark-iforest/python
        python setup.py sdist
        pip install dist/pyspark-iforest-2.4.0.99.tar.gz
        cd ../../
        mkdir ./src/baskerville/logs/
    - name: Lint with flake8
      run: |
        cd ./src
        flake8 . --count --ignore=C901,W503,W504,E226,E402 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        export PYTHONPATH="./src:./esretriever/src"
        pytest ./tests/unit
    - name: License check
      run: |
        python ./src/baskerville/util/licensing.py
